language: android
env:
  global:
  - MALLOC_ARENA_MAX=2
  - ADB_INSTALL_TIMEOUT=10
jdk:
- oraclejdk7
before_install:
- chmod +x gradlew
android:
  components:
  - tools
  - build-tools-23.0.2
  - extra-android-m2repository
  - android-23
script:
- ./gradlew assembleDebug
notifications:
  webhooks: https://hook.bearychat.com/=bw8Ss/travis/78c5f7dda4fc394348d3234ba48a7bb0